export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const GET_COMMIT = 'GET_COMMIT'
export const CHANGE_COMMIT = 'CHANGE_COMMIT'